### ISSUE TITLE
demo: discover new cool github projects

### ISSUE THREAD

**Issue by edublancas** [ploomber/doc#111]
create an app (we can use solara or panel, to be defined later) that allows discovering new cool github repos

we can use these endpoints from the API:

https://docs.github.com/en/rest/search/search?apiVersion=2022-11-28#search-repositories
https://docs.github.com/en/rest/search/search?apiVersion=2022-11-28#search-topics

note that they don't need a token (we'll be rate limited but that's ok:

```
curl -L \
  -H "Accept: application/vnd.github+json" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  "https://api.github.com/search/repositories?q=llm+monitoring"
```

the objective is to help me find interesting repositories, and it should prioritize the ones that are more popular (more stars, forks, more commits, etc).

sample conversation:

> show me cool machine learning repositories (note that the topic could be different, like C++ repositories)

Sure, here are the top ML repositories: (show name, description and basic stats)

> Tell me more about X

X is a project about... (create summary by feeding the readme)

> Are there any cool projects for LLM monitoring?

I found these LLM monitoring projects
(search again and find the most relevant results, show list along with some stats)

**Comment by edublancas** [comment]
let's use the OpenAI python package for the LLM and [lanceDB](https://github.com/lancedb/lancedb) for vector search

**Comment by lfunderburk** [comment]
Resolved by #113

**Comment by lfunderburk** [comment]
The current project is missing the ranking by stars
can add this shortly

**Comment by edublancas** [comment]
I remove the self-assignment, this is a different issue and still remains unassigned

**Comment by edublancas** [comment]
@lfunderburk I went through the open issues and yeah, it makes sense for you to continue working on this, assigning it

**Comment by edublancas** [comment]
v1 has been deployed, a few things we need to add for the next one:

- users should be able to ask "tell me more about repository X" where X is a repository that has been printed after performing a search. this should pass the README.md via openAI to summarize it
- once a user asks for more details about a specific repository, openAI should use the README to answer those questions, until a user performs another search


https://github.com/ploomber/doc/assets/989250/52e88d03-7eb4-46b8-b495-d2f86500d565



this is the same workflow that we have in the arxiv demo: https://github.com/ploomber/doc/tree/main/examples/solara/arxiv-chat
demo: https://summer-wind-5194.ploomberapp.io/
