### ISSUE TITLE
Error in news summarizer app

### ISSUE THREAD

**Issue by neelasha23** [ploomber/doc#123]
<img width="1314" alt="Screenshot 2024-02-26 at 11 55 21 AM" src="https://github.com/ploomber/doc/assets/29096135/7993b557-9fef-4b78-b483-3a38ef417bfd">

The README can also be improved by adding more details like the `OPENAI_API_KEY` needs to be set.

**Comment by edublancas** [comment]
is this a new deployment or the existing one?

**Comment by neelasha23** [comment]
New deployment

**Comment by edublancas** [comment]
did you run the command that's defined in the readme? https://github.com/ploomber/doc/tree/main/examples/panel/rag-news

**Comment by neelasha23** [comment]
We need to run it in local first? Ok checking

**Comment by edublancas** [comment]
yes

**Comment by edublancas** [comment]
there are probably some undocumented steps, please update the readme

you need an openai key to run the script locally, so it might be that
