### ISSUE TITLE
generate screenshots for our demos + `requirements.lock.txt`

### ISSUE THREAD

**Issue by edublancas** [ploomber/doc#131]
we have a new explore page where we'll showcase our examples

we need to generate one image per demo, no need to have them all at once, we can generate a batch and open a PR

also, no need to deploy them, we can run them locally and take the screenshot

since some examples might not work due to library API changes, we might need to update the code or downgrade versions, whatever is easier on each case, once we get them working, we should record the versions with `pip freeze > requirements.lock.txt`

**Comment by edublancas** [comment]
@yafimvo @idomic  we're gonna start taking screenshots of all out demos so they show up in the explore page. is there a recommended resolution for them?

**Comment by edublancas** [comment]
we did a lot of moving in the examples recently. if you find anything that's weird, please open an issue (e.g., broken links from the documentation to the examples) @neelasha23

**Comment by neelasha23** [comment]
where do we need to store the screenshots? In the same folder as each project? Or some common folder for all projects? @edublancas

**Comment by edublancas** [comment]
same repository, let's also add them to the readme, below the title and short explanation:

```md
# title

short explanation

-- add image here

explanation continues

```

let's wait for @idomic @yafimvo to give their feedback on the image size, you can start generating the requirements.lock.txt in the meantime

**Comment by neelasha23** [comment]
Added a couple of samples: https://github.com/ploomber/doc/pull/134
Please check if format is correct. 
@edublancas

**Comment by neelasha23** [comment]
1200 x 630:

![screenshot](https://github.com/ploomber/doc/assets/29096135/c0f21c2a-aa1e-4bce-9efa-ab0cab411c16)

1400 x 673:

![screenshot (2)](https://github.com/ploomber/doc/assets/29096135/f4898bfb-f82a-4588-bb95-7e6da5c2d109)

I think the 1st one is not that good and we should go for a bit higher resolution? @edublancas

**Comment by neelasha23** [comment]
Also, do we need to add all example to the explore page? That means we need to keep the applications deployed? Any specific account in which to deploy? @edublancas

**Comment by edublancas** [comment]
re resolution: yeah, you can experiment a bit and decide which resolution and aspect ratio is best. also, you might wanna zoom in using the browser so the text is more readable

re deployments: good point. I think for now, let's link to the source code in this repository. [example](https://github.com/ploomber/doc/tree/main/examples/fastapi/basic-app)

I also realized that some of our apps are APIs (no UI), in that case, we can create an image with the framework's logo (flask, fastapi, etc)

**Comment by edublancas** [comment]
@neelasha23 what's the status? please open small PRs, don't wait to have all screenshots

**Comment by neelasha23** [comment]
> re deployments: good point. I think for now, let's link to the source code in this repository. [example](https://github.com/ploomber/doc/tree/main/examples/fastapi/basic-app)

I think the `link` can only be a valid app URL as per the docs. passing any other link is throwing error:
```
{"type":"https://cloud-prod.ploomber.io/docs","title":"Bad Request","detail":"Invalid project URL."}
```

@edublancas

**Comment by edublancas** [comment]
@yafimvo @idomic can we remove this URL validation. some of our examples are not deployed anymore and we want to link to the README.md, we might decide to deploy them at some point but right now it'd be easier to just link to the readme

@neelasha23 please work on https://github.com/ploomber/doc/issues/139 until we unblock this

**Comment by edublancas** [comment]
ok, let's do another format then

**Comment by neelasha23** [comment]
I also tried different sizes but there is still some padding around the image. I'm not sure if it was designed that way. maybe the padding can be reduced?

<img width="437" alt="Screenshot 2024-03-06 at 11 06 47 PM" src="https://github.com/ploomber/doc/assets/29096135/c78395ce-cf16-4e0e-b392-13c0092a1582">

@yafimvo @edublancas

**Comment by neelasha23** [comment]
> yes, the padding is part of the design. why do we want to reduce it?

The text would look a bit clearer and bigger if we reduce a bit of the padding. wdyt @edublancas

**Comment by edublancas** [comment]
> Yes, in this case, I need to add one more parameter - project_name.

why is a new parameter needed?

>Do we still want the button text would be View App even for repo links?

> As for the default images, I can create a mechanism that if there is no image we can show the framework logo.

sounds good

> yes, the padding is part of the design. why do we want to reduce it?

I think the padding is fine

> As part of this PR I'll also add webp support.

sounds good

**Comment by edublancas** [comment]
1. that's ok, you can ignore those
2. ignore that
3. ignore that as well

we can come back to those later if needed.

are those the only ones left?

**Comment by neelasha23** [comment]
yes i have added all the rest @edublancas

**Comment by edublancas** [comment]
we're not adding .zip for all examples, only for the ones uses in the frontend
