### ISSUE TITLE
Rename voila notebooks to `app.ipynb`

### ISSUE THREAD

**Issue by neelasha23** [ploomber/doc#135]
Voila deployments throw error if `app.py` is not found in the zip file. Some of the examples contain `notebook.ipynb` instead of `app.ipynb`. We need to rename these.

**Comment by edublancas** [comment]
where did you see the error? AFAIK, you can deploy an ipynb + requirements.txt or a zip, and the zip expects an ipynb.

voila deploys from ipynb files, so I don't think we are checking for .py files

@94rain I think you worked on adding support for voila deployments via zip, right? can you comment on this? how are we validating the zip file?

**Comment by neelasha23** [comment]
I meant `app.ipynb`. i tried creating a zip named `notebook.zip` as well as `app.zip` I see the error in both:

<img width="1176" alt="Screenshot 2024-03-04 at 11 39 35 PM" src="https://github.com/ploomber/doc/assets/29096135/3d3abff6-282f-422f-8ade-591be4dfa7b3">

<img width="1195" alt="Screenshot 2024-03-04 at 11 39 49 PM" src="https://github.com/ploomber/doc/assets/29096135/de5992ca-d406-4ca3-af16-89ca3f2855d8">

**Comment by edublancas** [comment]
ok, yes. we need to rename from `{anyname}.ipynb` -> `app.ipynb`
