### ISSUE TITLE
chat with csv example should ask for a key if missing

### ISSUE THREAD

**Issue by edublancas** [ploomber/doc#152]
currently, the chat with a csv example breaks if it doesn't have an API key. instead it should ask for one

![image](https://github.com/ploomber/doc/assets/989250/2edf3ed3-386d-4a97-bce9-75caeb654e99)

**Comment by neelasha23** [comment]
I have added a print statement with reference link of setting env variables (in the linked PR).
But did you mean we need to display an input text box in which users can input the key? 
@edublancas

**Comment by edublancas** [comment]
> But did you mean we need to display an input text box in which users can input the key?

yes
