### ISSUE TITLE
ensure that cli examples do not require env vars

### ISSUE THREAD

**Issue by edublancas** [ploomber/doc#162]
we recently added instructions for deploying with the CLI: https://docs.cloud.ploomber.io/en/latest/apps/voila.html

however, we must ensure that the examples we show *do not require* env vars or API keys, otherwise they'll fail. for example, the voila "chat with csv" app requires an openai API key

**Comment by bryannho** [comment]
@edublancas I just deployed each example mentioned in the CLI instructions for its framework:
- `panel/data-viz`
- `streamlit/data-viz`
- `voila/chat-with-csv`
- `solara/gpt-4-tokenizer`
- `dash/clinical-analytics`
- `shiny-r/shiny-r-data-visualization`
- `docker/jupyterlab`
- `docker/mlflow`

They all deploy and work fine without env vars or API keys except for `voila/chat-with-csv`. But @neelasha23 fixed that I don't think we need to make any more changes to the documentation.

**Comment by edublancas** [comment]
awesome, thanks for checking
