### ISSUE TITLE
finalize customer bot example

### ISSUE THREAD

**Issue by edublancas** [ploomber/doc#163]
follow up of https://github.com/ploomber/doc/pull/157

- social media posts
- add to explore page, add to docs ([see here](https://docs.cloud.ploomber.io/en/latest/apps/panel.html#examples))

**Comment by neelasha23** [comment]
1. Drafted social media posts
2. Added project to Explore page
3. Added to Panel docs: https://github.com/ploomber/doc/pull/165

@edublancas
