### ISSUE TITLE
chat with pdf example

### ISSUE THREAD

**Issue by edublancas** [ploomber/doc#167]
create a "chat with a pdf" app using chainlit. there's a similar app we built that you can use as reference: https://github.com/ploomber/doc/tree/main/examples/panel/chat-with-pdf

let's first build a simple one and then we can add some extra features:

to parse the PDF, we can use our recently launched API: https://docs.cloud.ploomber.io/en/latest/features/document-processing.html

this will return the parsed text, then we can write some logic to create embeddings using OpenAI and store the embeddings in [LanceDB](https://github.com/lancedb/lancedb), and then we can write the logic to answer questions

here's an example that also uses lancedb: https://github.com/ploomber/doc/blob/main/notebooks/document-qa-basic.ipynb

**Comment by neelasha23** [comment]
The PR is ready for review. But there is some issue in the deployments ( I tried deploying the basic Chainlit application also and faced the same issue)

<img width="1110" alt="Screenshot 2024-04-06 at 9 46 12 PM" src="https://github.com/ploomber/doc/assets/29096135/a000ec3d-c9b7-4b6e-80e8-27ea8e1fcc37">

<img width="1018" alt="Screenshot 2024-04-06 at 9 46 17 PM" src="https://github.com/ploomber/doc/assets/29096135/a1b8d00c-add4-4fab-a030-b93289f5dfc3">


@edublancas

**Comment by edublancas** [comment]
@neelasha23 we found the issue and are testing a fix. will ping you once it's fixed

**Comment by edublancas** [comment]
@neelasha23 chainlit apps are working again now
