### ISSUE TITLE
document runtime versions and how to customize

### ISSUE THREAD

**Issue by edublancas** [ploomber/doc#175]
we should mention in all our supported frameworks that they will run with Python 3.11 

- dash
- panel
- solara
- streamlit
- voila

we also need to mention that if users want to change the version (or use another base image), they can use Docker deployments, we can add small examples for each of those frameworks that use Dockerfile (sample dockerfiles are available in our backend repo)

**Comment by neelasha23** [comment]
I'm not sure of this part: `we can add small examples for each of those frameworks`. We want to add the `Dockerfile` format as in the cloud-backend repo? like all the instructions or just the version part?
Can you check this [PR](https://github.com/ploomber/doc/pull/196) if this is the correct format?

@edublancas

**Comment by edublancas** [comment]
added a comment on the PR

**Comment by neelasha23** [comment]
I get this warning when deploying the sample Dash application:

<img width="742" alt="Screenshot 2024-04-19 at 4 12 24 PM" src="https://github.com/ploomber/doc/assets/29096135/311d2e6b-d039-4f74-bbbd-4635ca69a23c">

But `plotly` is a required dependency of `dash`, so I didn't include it in `requirements.txt`. Do we still need to include `plotly` in the file? Else users might get confused?

@edublancas

**Comment by edublancas** [comment]
yeah that's a fair point. I thought about it as well

the problem is that we'd have to create a mapping of "if dash installed, then plotly also installed". on the one hand, it's better to be explicit and users should put plotly, on the other, they might be confused.

I think let's keep it as is for now, but I see your point.

**Comment by neelasha23** [comment]
I have added examples for Panel, Dash, Solara and streamlit in the PR.  For Voila apps I get this error:

```
  File "/Users/neelashasen/Dev/doc/examples/voila/docker-based/env/lib/python3.11/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/neelashasen/Dev/doc/examples/voila/docker-based/env/lib/python3.11/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/neelashasen/Dev/doc/examples/voila/docker-based/env/lib/python3.11/site-packages/jinja2/loaders.py", line 575, in load
    raise TemplateNotFound(name)
jinja2.exceptions.TemplateNotFound: index.html.j2
```

I'll fix it and open a separate PR for `Shiny R` and `Voila`

@edublancas

**Comment by edublancas** [comment]
oh, I see why you didn't put "closes #x" in your PR, opening this again then

try doing some quick debugging, if you encounter issues, feel free to open an issue in Voila's repo

**Comment by neelasha23** [comment]
The issue was with lastest JupyerLab version. Opened an issue with Voila: https://github.com/voila-dashboards/voila/issues/1465

@edublancas
