### ISSUE TITLE
update doc, settings button has been moved

### ISSUE THREAD

**Issue by edublancas** [ploomber/doc#181]
we did a little UI change, the SETTINGS button was replaced by the ANALYTICS REPORT one:

![image](https://github.com/ploomber/doc/assets/989250/630ca023-bc6e-4718-86f4-8902a80d8621)

we need to check if we have images referencing this button and update them (the location for the settings is now in the `...` menu)

also, I remember we have some mentions to the `SETTINGS` button (in text), we need to replace them for something like click on `...` then `Settings`.

**Comment by neelasha23** [comment]
https://docs.cloud.ploomber.io/en/latest/user-guide/resources.html
https://docs.cloud.ploomber.io/en/latest/quickstart/app.html
