### ISSUE TITLE
Update images on Deploy app page

### ISSUE THREAD

**Issue by neelasha23** [ploomber/doc#192]
1. Fill out the Form (Environment variables now replaced with Secrets)
2. In the last image `Settings` button is now replaced by `Analytics Report`

https://docs.cloud.ploomber.io/en/latest/quickstart/app.html

**Comment by bryannho** [comment]
@neelasha23 @edublancas yes I missed 1. so that should be updated

I did find another issue on the serverless page: https://docs.cloud.ploomber.io/en/latest/features/serverless-fns.html

The title `Serveless functions` should be `Serverless functions`

**Comment by neelasha23** [comment]
> The title `Serveless functions` should be `Serverless functions`

Yes I saw that too. I'll be updating in the next PR
