### ISSUE TITLE
investigate auth_secret

### ISSUE THREAD

**Issue by edublancas** [ploomber/doc#207]
see this: https://github.com/ploomber/doc/pull/205#discussion_r1580161284

**Comment by edublancas** [comment]
I did some research, I think AUTH_SECRET is used to verify the session IDs. I deployed, logged in, then deployed again (but changed AUTH_SECRET) and the app still worked but it logged me out

I'll update the docs but spent a few minutes doing some research to see if I missed anything

**Comment by bryannho** [comment]
@edublancas I can update the docs if you haven't yet

**Comment by edublancas** [comment]
yeah I didn't find anything clear as well. but based on my experiments, seems like it's used to sign session tokens

no worries, we can close this now
