### ISSUE TITLE
a more compelling demo for socials

### ISSUE THREAD

**Issue by edublancas** [ploomber/doc#24]
we need to create a more compelling demo to share on social media. we can use any of the supported frameworks. the objective is to craft a great social media post to attract people to start building in our platform.

unlike the other open issues (like https://github.com/ploomber/doc/issues/23 https://github.com/ploomber/doc/issues/14). this one should be a more complex application, it's fine if it takes longer to build

@neelasha23 please share your ideas. we can allocate some budget for this (e.g., use openAI for the demo)

ideas:

- chat with your documents (upload some documents and then chat with them)
- an improved version of "chat with your csv"
- maybe image generation with stable diffusion? (e.g., generate images with certain style by uploading a few examples) - this one will be a bit harder since we do not have GPU support yet

**Comment by neelasha23** [comment]
Here are some ideas related to LLMs:

1. Visualisation generation: This looks interesting and complex https://medium.com/@c17hawke/lida-automatically-generate-visualization-and-with-llms-the-future-of-data-visualization-6bc556876b46
Utilises LLM's code generation capability for generating visualisations using most common libraries like `seaborn`, `matplotlib`, `altair`, etc. It can also perform visualisation explanations, EDA etc.

2. Workflow automation: e.g, analyse a complaint email, classify the email, and perform an action/ write response. Reference: https://achan2013.medium.com/approaches-in-using-generative-ai-for-workflow-automation-part-1-15aea74a3d21

3. Generating social media marketing content in multiple languages.

4. Chatting with your documents like you mentioned (this can also include training on custom data in a fast and scalable manner)

**Comment by edublancas** [comment]
let's go with visualization generation

let's use solara since it provides nice UI capabilities, here's how to build a chat interface: https://itnext.io/python-how-to-build-a-chatgpt-interface-in-solara-fd6a1e15ef95

I already built something like this with Voila, you can copy the code: https://github.com/ploomber/doc/blob/main/examples/voila/chat-with-csv/notebook.ipynb

I think let's first get the basic solara app up and running (with the same capabilities than the one I developed for Voila), once we have that, we can start adding more features

**Comment by edublancas** [comment]
any updates here?

**Comment by neelasha23** [comment]
I'll push a draft in a day. Spent some time understanding the Solara components

**Comment by edublancas** [comment]
sounds good

**Comment by edublancas** [comment]
I guess the conclusion for this one was the "chat with a csv" so I'll close this for now
