### ISSUE TITLE
udpate docs

### ISSUE THREAD

**Issue by edublancas** [ploomber/doc#280]
we need to remove the warning since docker deployments are now allowed on community: https://docs.cloud.ploomber.io/en/latest/apps/docker.html

**Comment by LatentDream** [comment]
On it

**Comment by LatentDream** [comment]
I'll update the debugger also

**Comment by edublancas** [comment]
awesome

**Comment by LatentDream** [comment]
I Double check the pricing on the main site. We don't mention docker on Pro. So

**Comment by LatentDream** [comment]
Yeah, I saw that I forgot it
