### ISSUE TITLE
Issue with sample notebook - chat with your csv

### ISSUE THREAD

**Issue by idomic** [ploomber/doc#29]
The sample loads, but shows an error in Cell 3:
<img width="1424" alt="Screen Shot 2023-10-17 at 9 14 31 AM" src="https://github.com/ploomber/doc/assets/11596985/29e7086f-bf35-4192-8dd9-466a9e927fc2">

**Comment by edublancas** [comment]
did you add the open ai key? if not, that might be the reason.

**Comment by edublancas** [comment]
I'm not sure about this. This is Voila's default behavior for security reasons; all web frameworks hide tracebacks from the front end because they might contain sensitive information.

but the traceback should be accessible from the web service logs in the UI
