### ISSUE TITLE
Docker build not completing

### ISSUE THREAD

**Issue by neelasha23** [ploomber/doc#45]
Uploaded the `app.zip` in this project https://github.com/ploomber/doc/pull/44

Docker build is not completing and I dont see any errors in logs also

<img width="803" alt="Screenshot 2023-11-14 at 10 58 02 PM" src="https://github.com/ploomber/doc/assets/29096135/9b442bb3-eef7-4f26-9b9d-f1bf786c0d07">

@idomic

**Comment by edublancas** [comment]
@idomic I'm trying to find the logs for this but I'm unable to find the ECS task, maybe it was never triggered?

@neelasha23 what happens if you delete the project and try again? are the logs empty? do you see any errors?

**Comment by edublancas** [comment]
@idomic 

I reproduced the problem. I tried to deploy this app: [app.zip](https://github.com/ploomber/doc/files/13357703/app.zip)

left the process running for >10 minutes and it never got past the docker build step:

![image](https://github.com/ploomber/doc/assets/989250/5d121549-7de6-49bb-a7eb-f5d5f257c6f3)

the logs don't show any errors: https://us-east-1.console.aws.amazon.com/ecs/v2/clusters/ECSStackProd-ClusterEB0386A7-06zVhW4xZnYy/tasks/5d71456e3698428583db1a934bc139c9/logs?region=us-east-1

**Comment by edublancas** [comment]
This is a pretty simple app (it's an example); there are no big dependencies being installed or datasets being copied. We've deployed it before with no issues. 1GB for docker builds is too small.

In any case, the error should be visible from the menu. Otherwise, it leaves the user hanging. thinking that the process is still going on

**Comment by edublancas** [comment]
update: tried again with an even simpler app and got the memory issue again

**Comment by edublancas** [comment]
@neelasha23 thanks for reporting this. we'll increate the memory assigned to the docker build. we'll update when it's fixed.

**Comment by edublancas** [comment]
working well now! 

![image](https://github.com/ploomber/doc/assets/989250/d5dc8125-acef-4556-9d5f-42e4f3fb3afd)

@neelasha23 please try re-deploying
