### ISSUE TITLE
Project hangs in waiting-for-traffic

### ISSUE THREAD

**Issue by FelipeCabelloE** [ploomber/doc#50]
After deploying a project with git actions, the build process is hanging in the "waiting-for-traffic" state.

There are no logs, and the only clickable option I see is to delete the project.

The project is [dawn-math-8053](https://www.platform.ploomber.io/dashboards/dawn-math-8053/) and is deployed from [solarathon-team5](https://github.com/FelipeCabelloE/solarathon-team5).

**Comment by edublancas** [comment]
@idomic can someone look at this?

I think it's either that the cluster is going over capacity or that the app is using too many resources and maybe the cluster is shutting it down and then fails to start again

**Comment by edublancas** [comment]
hey @FelipeCabelloE a few things that can help us debug things:

- did the at work at all and then stopped working or it never worked in the first place
- have you tried deleting the app and trying to deploy it again

**Comment by FelipeCabelloE** [comment]
Hello.
I ended up creating anothe account and then had no problems at all.

Many thanks for the support.
