### ISSUE TITLE
add deployment guide to Panel docs

### ISSUE THREAD

**Issue by edublancas** [ploomber/doc#59]
we recently added support for [panel](https://docs.cloud.ploomber.io/en/latest/apps/panel.html) to ploomber cloud, so we should add a tutorial to Panel's documentation on how to deploy apps to ploomber cloud (using the CLI and the web app).

I already messaged the Panel creator (Philipp Rudiger), and he approved it.

we can do something similar to what we did for Voila: https://voila.readthedocs.io/en/latest/deploy.html

add a tutorial to their docs and link back to ours

**Comment by edublancas** [comment]
hey @neelasha23 please prioritize this task

**Comment by neelasha23** [comment]
sure!

**Comment by neelasha23** [comment]
I have created a draft PR: https://github.com/holoviz/panel/pull/6182
Please review the content. The docs local build is yet to complete so the HTML output verification is pending. Also, I need to reduce the dimensions of the logo.
@edublancas

**Comment by edublancas** [comment]
looks good, just add a bit more context to the PR, tag me, and mention that I've spoken to Philipp Rudiger and he was ok with us opening a PR

**Comment by neelasha23** [comment]
The PR is merged but it's not up on the [docs](https://panel.holoviz.org/how_to/deployment/index.html). as of now.
Once it is, I'll add a link to our docs. @edublancas

**Comment by edublancas** [comment]
added a comment to the Panel PR to ask if the docs are deployed whenever there's a new Panel release

**Comment by edublancas** [comment]
this has been released: https://panel.holoviz.org/how_to/deployment/index.html let's add the link so we can close this
