### ISSUE TITLE
demo: LLM monitoring with weights and biases

### ISSUE THREAD

**Issue by edublancas** [ploomber/doc#82]
deploy a sentiment classifier powered by OpenAI, wrap it into a flask API and monitor it with [weights and biases](https://wandb.ai/site/monitoring)

I briefly read weights and biases docs and it seems like the tool is meant for monitoring LLMs in production but we'll have to do more research

requirements

- sample code
- blog post

**Comment by edublancas** [comment]
sample code: [app.py.zip](https://github.com/ploomber/doc/files/14070402/app.py.zip)

**Comment by lfunderburk** [comment]
This issue is a bit different from what the current monitoring with wandb is doing so will mention it here

Work in a similar direction #113

**Comment by lfunderburk** [comment]
Blog associated 

https://github.com/ploomber/ploomber.io/pull/132

**Comment by edublancas** [comment]
closed by https://github.com/ploomber/doc/commit/0dd1c54abb8daea9a1fa7c2f75ef6ea423e13b27
