### ISSUE TITLE
demo: shiny app (R)

### ISSUE THREAD

**Issue by edublancas** [ploomber/doc#84]
same as https://github.com/ploomber/doc/issues/83 but for R

**Comment by edublancas** [comment]
@lfunderburk I'll take over this

there is already an example: https://github.com/ploomber/doc/tree/main/examples/shiny-r

but it hasn't been documented because there's a fix we need to do to the platform for this to work

**Comment by lfunderburk** [comment]
Ok understand
Will remove assignment from me

**Comment by lfunderburk** [comment]
Oh see you already did it

**Comment by edublancas** [comment]
done https://github.com/ploomber/doc/commit/2e3dec3fea812615b0597a960113c55cb5a42b91
