### ISSUE TITLE
demo: hashtag generator

### ISSUE THREAD

**Issue by neelasha23** [ploomber/doc#89]
Upload an image and generate hashtags. This can be done in 2 steps:
1. Image captioning
2. Use openAI to generate the hashtags from the caption.

**Comment by neelasha23** [comment]
Any thoughts? @edublancas

**Comment by edublancas** [comment]
I assigned https://github.com/ploomber/doc/issues/83 in the meantime while we discuss this.

when you say hashtags you mean twitter hashtags? I'm not following the use case

**Comment by neelasha23** [comment]
hashtags for photo apps like Instagram
