### ISSUE TITLE
demo: book recommender

### ISSUE THREAD

**Issue by edublancas** [ploomber/doc#95]
a RAG using OpenAI that recommends you books

we can use this dataset: https://www.kaggle.com/datasets/cristaliss/ultimate-book-collection-top-100-books-up-to-2023

**Comment by edublancas** [comment]
@bryannho you started working on this, right? please share with @neelasha23 any progress you have

**Comment by neelasha23** [comment]
have linked a PR. I still see a lot of scope for improvement like :

1. Recommend books similar to `some-book`.
2. Filter based on columns number of pages, rating score, current readers, price etc.

Should I add these as well?

@edublancas

**Comment by edublancas** [comment]
let's ship v1 and then we can discuss improvements
