### ISSUE TITLE
demo: stock market data analyst

### ISSUE THREAD

**Issue by edublancas** [ploomber/doc#97]
build a chatbot that helps you do stock market analysis

we can start with a simple one that can retrieve stock prices

examples

1. give me apple's stock price from two weeks ago to now
2. overlay apple and Microsoft from jan 2020 to dec 2021

 we can use this package: https://github.com/ranaroussi/yfinance

**Comment by edublancas** [comment]
we can use either panel:

https://panel.holoviz.org/reference/chat/ChatInterface.html

or solara:

https://solara.dev/api/chat

**Comment by lfunderburk** [comment]
Hi @edublancas 
Picking this up for next week

**Comment by edublancas** [comment]
Please check my slack message. There won't be a demo for next week, but a blog post

**Comment by lfunderburk** [comment]
oh ok

**Comment by edublancas** [comment]
let's start with a very basic feature: the app should be able to pull and plot data for a specific company:


1. give me apple's stock price from two weeks ago to now
2. overlay apple and Microsoft from jan 2020 to dec 2021

and that's it

**Comment by edublancas** [comment]
closed by https://github.com/ploomber/doc/pull/124
